version: "3"

services:
  model:
    build:
      context: ./model
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./model/data:/app/data
      - ./model/src:/app/src
      - ./model/vectorstores:/app/vectorstores

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - model

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8082:80"
