version: "3"

services:
  model:
    build:
      context: ./model
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./model/data:/app/data
      - ./model/src:/app/src
      - ./model/vectorstores:/app/vectorstores

  # backend:
  #   build:
  #     context: ./backend   # Point to the backend directory
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - model
