version: "3"

services:
  model:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./vectorstores:/app/vectorstores
#  backend:
#    build:
#      context: ./path-to-backend
#      dockerfile: Dockerfile-backend
#    depends_on:
#      - model
